export type Lang = "en" | "fa";

export const CONTACT_EMAIL = "hello@mahsatech.com"; // TODO: replace with your real email

const en = {
  nav: { services: "Services", tools: "Tools", marketing: "Marketing", principles: "Principles", team: "Team", contact: "Contact" },
  brand: ["Mahsa", "Tech"],
  badge: "Open for new projects",
  heroPre: "We build",
  words: ["websites", "web apps", "mobile apps", "AI products", "smart contracts"],
  lead: "MahsaTech is a small team of developers and marketers crafting fast, beautiful and scalable digital products — web, mobile, blockchain and AI. Direct communication, zero agency overhead.",
  cta1: "Start a project",
  cta2: "Explore services",
  stats: [
    { n: 2, suffix: "", label: "Dedicated developers" },
    { n: 6, suffix: "", label: "Core disciplines" },
    { n: 20, suffix: "+", label: "Technologies" },
    { n: 24, suffix: "h", label: "Reply time" },
  ],
  servicesTitle: "Our Services",
  servicesSub: "From idea to launch, we're with you every step.",
  items: [
    { title: "Web Development", text: "Design and development of modern websites with cutting-edge technologies.", tags: ["React & Next.js", "TypeScript", "Responsive Design", "SEO Optimization"] },
    { title: "Mobile Apps", text: "Native and cross-platform mobile applications.", tags: ["React Native", "Flutter", "iOS & Android", "PWA"] },
    { title: "Blockchain", text: "Smart contracts and decentralized platforms.", tags: ["Solidity", "Web3", "Smart Contracts", "DApps"] },
    { title: "AI Solutions", text: "Practical AI and machine learning solutions for your product.", tags: ["Machine Learning", "NLP", "Computer Vision", "AI Integration"] },
    { title: "UI/UX Design", text: "Beautiful interfaces and a seamless user experience.", tags: ["User Research", "Wireframing", "Prototyping", "Design Systems"] },
    { title: "Technical Consulting", text: "Guidance in choosing the right technical solutions.", tags: ["Architecture Design", "Tech Stack", "Performance", "Scalability"] },
  ],
  toolsTitle: "Our Tools",
  toolsSub: "The technologies we build the future with.",
  groups: [
    { name: "Frontend", tools: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Three.js", "Framer Motion"] },
    { name: "Mobile", tools: ["React Native", "Flutter"] },
    { name: "Backend", tools: ["Node.js", "Python", "PostgreSQL"] },
    { name: "Blockchain", tools: ["Solidity", "Web3.js", "Ethers.js", "Hardhat"] },
    { name: "AI & Quantum", tools: ["PyTorch", "TensorFlow", "Qiskit"] },
    { name: "DevOps", tools: ["Git", "Docker", "Vercel"] },
    { name: "Design", tools: ["Figma", "UI/UX Design"] },
  ],
  marketingTitle: "Marketing",
  marketingSub: "We don't just build it — we help people find it.",
  marketing: [
    { title: "Brand & Positioning", text: "A clear story and identity that make your product stand out." },
    { title: "SEO & Content", text: "Search-friendly pages and content that bring in the right audience." },
    { title: "Social Media", text: "Consistent campaigns and creatives across your channels." },
    { title: "Launch Strategy", text: "A go-to-market plan so launch day actually brings users." },
  ],
  principlesTitle: "Our Principles",
  principlesSub: "The values that guide our team.",
  principles: [
    { title: "Silence & Precision", alt: "", text: "We write code quietly and precisely." },
    { title: "Transparency", alt: "", text: "We believe in transparency." },
    { title: "AI Collaboration", alt: "", text: "We see AI as a teammate, not a tool." },
  ],
  processTitle: "How we work",
  processSub: "A simple, transparent process from first call to launch.",
  steps: [
    { title: "Discovery", text: "We listen, ask questions and define scope, goals and timeline." },
    { title: "Design", text: "Wireframes and a clickable prototype you approve before we code." },
    { title: "Build", text: "Regular demos while we ship clean, tested, production-ready code." },
    { title: "Launch & Care", text: "Deployment, monitoring and ongoing support after go-live." },
  ],
  teamTitle: "The team",
  teamSub: "Developers and marketers, one shared standard of quality.",
  people: [
    { name: "Mahsa Karimi", role: "Frontend & Blockchain Developer", github: "https://github.com/mhkarimi78", linkedin: "https://www.linkedin.com/in/mahsa-karimii/" },
    { name: "Ahmadreza Hamidifard", role: "Backend & DevOps Developer", github: "https://github.com/AhmadrezaHamidi", linkedin: "https://www.linkedin.com/in/ahmad-hamidi/" },
    { name: "Tina Karimi", role: "Marketing Team", github: "", linkedin: "" },
  ],
  ctaTitle: "Have a project in mind?",
  ctaText: "Tell us about it — we'll reply within 24 hours with questions and next steps.",
  form: { name: "Your name", email: "Your email", message: "Tell us about your project", send: "Send message", hint: "Opens your email app with the message ready to send." },
  rights: "All rights reserved.",
};

export type Content = typeof en;

const fa: Content = {
  nav: { services: "خدمات", tools: "ابزارها", marketing: "بازاریابی", principles: "اصول", team: "تیم", contact: "تماس" },
  brand: ["مهسا", "تک"],
  badge: "پذیرای پروژه‌های جدید هستیم",
  heroPre: "ما می‌سازیم",
  words: ["وب‌سایت", "وب‌اپ", "اپ موبایل", "ابزار هوشمند", "قرارداد هوشمند"],
  lead: "مهساتک، تیم کوچک ما از توسعه‌دهنده و بازاریاب، برای ساخت محصولات دیجیتال سریع، زیبا و مقیاس‌پذیر است؛ از وب و موبایل تا بلاکچین و هوش مصنوعی. بدون واسطه و بدون هزینه‌های اضافی، مستقیم با خود توسعه‌دهنده‌ها کار می‌کنید.",
  cta1: "پروژه‌تان را شروع کنیم",
  cta2: "خدمات ما را ببینید",
  stats: [
    { n: 2, suffix: "", label: "توسعه‌دهنده" },
    { n: 6, suffix: "", label: "حوزه تخصصی" },
    { n: 20, suffix: "+", label: "فناوری" },
    { n: 24, suffix: " ساعت", label: "زمان پاسخ‌گویی" },
  ],
  servicesTitle: "خدمات ما",
  servicesSub: "از ایده تا اجرا، در کنار شما هستیم.",
  items: [
    { title: "توسعه وب", text: "طراحی و توسعه وب‌سایت‌های مدرن با تکنولوژی‌های روز دنیا.", tags: ["React & Next.js", "TypeScript", "Responsive Design", "SEO Optimization"] },
    { title: "اپلیکیشن موبایل", text: "ساخت اپلیکیشن‌های موبایل بومی و کراس‌پلتفرم.", tags: ["React Native", "Flutter", "iOS & Android", "PWA"] },
    { title: "بلاکچین", text: "توسعه قراردادهای هوشمند و پلتفرم‌های غیرمتمرکز.", tags: ["Solidity", "Web3", "Smart Contracts", "DApps"] },
    { title: "هوش مصنوعی", text: "پیاده‌سازی راهکارهای هوش مصنوعی و یادگیری ماشین.", tags: ["Machine Learning", "NLP", "Computer Vision", "AI Integration"] },
    { title: "طراحی UI/UX", text: "طراحی رابط کاربری زیبا و تجربه کاربری بی‌نظیر.", tags: ["User Research", "Wireframing", "Prototyping", "Design Systems"] },
    { title: "مشاوره فنی", text: "مشاوره و راهنمایی در انتخاب بهترین راهکارهای فنی.", tags: ["Architecture Design", "Tech Stack", "Performance", "Scalability"] },
  ],
  toolsTitle: "ابزارهای ما",
  toolsSub: "فناوری‌هایی که با آن‌ها فردا را می‌سازیم.",
  groups: [
    { name: "فرانت‌اند", tools: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Three.js", "Framer Motion"] },
    { name: "موبایل", tools: ["React Native", "Flutter"] },
    { name: "بک‌اند", tools: ["Node.js", "Python", "PostgreSQL"] },
    { name: "بلاکچین", tools: ["Solidity", "Web3.js", "Ethers.js", "Hardhat"] },
    { name: "هوش مصنوعی و کوانتوم", tools: ["PyTorch", "TensorFlow", "Qiskit"] },
    { name: "دواپس", tools: ["Git", "Docker", "Vercel"] },
    { name: "طراحی", tools: ["Figma", "UI/UX Design"] },
  ],
  marketingTitle: "بازاریابی",
  marketingSub: "فقط نمی‌سازیم؛ کمک می‌کنیم دیده هم بشود.",
  marketing: [
    { title: "برندسازی و جایگاه‌یابی", text: "روایت و هویتی روشن که محصول شما را از بقیه متمایز می‌کند." },
    { title: "سئو و تولید محتوا", text: "صفحه‌ها و محتوایی دوستدار موتور جست‌وجو که مخاطب درست را جذب می‌کند." },
    { title: "شبکه‌های اجتماعی", text: "کمپین‌ها و طرح‌های منسجم برای تمام کانال‌های شما." },
    { title: "استراتژی عرضه", text: "برنامه‌ای برای ورود به بازار، تا روز انتشار واقعاً کاربر بیاورد." },
  ],
  principlesTitle: "اصول ما",
  principlesSub: "ارزش‌هایی که جمع ما را هدایت می‌کنند.",
  principles: [
    { title: "سکوت و دقت", alt: "Silence & Precision", text: "ما با سکوت و دقت کد می‌نویسیم." },
    { title: "شفافیت", alt: "Transparency", text: "ما به شفافیت اعتقاد داریم." },
    { title: "همکاری با هوش مصنوعی", alt: "AI Collaboration", text: "ما هوش مصنوعی را همکار می‌دانیم، نه ابزار." },
  ],
  processTitle: "مسیر همکاری",
  processSub: "مسیری ساده و شفاف، از اولین گفت‌وگو تا روز انتشار.",
  steps: [
    { title: "شناخت نیاز", text: "اول گوش می‌دهیم و سؤال می‌پرسیم تا هدف، دامنه‌ی کار و زمان‌بندی روشن شود." },
    { title: "طراحی", text: "پیش از نوشتن کد، طرح و نمونه‌ی اولیه‌ی قابل‌کلیک را می‌بینید و تأیید می‌کنید." },
    { title: "توسعه", text: "کدِ تمیز و تست‌شده می‌نویسیم و در طول مسیر، پیشرفت کار را به شما نشان می‌دهیم." },
    { title: "انتشار و پشتیبانی", text: "پروژه را منتشر می‌کنیم و بعد از آن هم کنارتان می‌مانیم." },
  ],
  teamTitle: "تیم ما",
  teamSub: "توسعه‌دهنده و بازاریاب، با یک معیار مشترک برای کیفیت.",
  people: [
    { name: "مهسا کریمی", role: "توسعه‌دهنده فرانت‌اند و بلاکچین", github: "https://github.com/mhkarimi78", linkedin: "https://www.linkedin.com/in/mahsa-karimii/" },
    { name: "احمدرضا حمیدی‌فرد", role: "توسعه‌دهنده بک‌اند و دواپس", github: "https://github.com/AhmadrezaHamidi", linkedin: "https://www.linkedin.com/in/ahmad-hamidi/" },
    { name: "تینا کریمی", role: "تیم بازاریابی", github: "", linkedin: "" },
  ],
  ctaTitle: "پروژه‌ای در ذهن دارید؟",
  ctaText: "ایده‌تان را برایمان بنویسید؛ ظرف ۲۴ ساعت جواب می‌دهیم و قدم بعدی را با هم مشخص می‌کنیم.",
  form: { name: "نام و نام خانوادگی", email: "ایمیل", message: "درباره‌ی پروژه‌تان بگویید", send: "ارسال پیام", hint: "با زدن این دکمه، برنامه‌ی ایمیل شما با متن آماده باز می‌شود." },
  rights: "تمام حقوق محفوظ است.",
};

export const content: Record<Lang, Content> = { en, fa };
